#!/bin/bash

set -e

if [ $(docker ps -a | wc -l) -gt 1 ]; then
	echo 'Removing all docker containers...'
	[ $(docker ps -a | grep Up | wc -l) -gt 0 ] && docker kill $(docker ps -a | grep Up | awk -F ' ' '{print $1}')
	docker rm $(docker ps -a | tail -n+2 | awk -F ' ' '{print $1}')
fi

if [ $(docker images | wc -l) -gt 1 ]; then
	echo 'Removing all docker images...'
	docker rmi -f $(docker images | tail -n+2 | awk -F ' ' '{print $3}')
fi

echo 'Done'
