#!/bin/bash

set -e

all=0;
while getopts a opt
do
	case "$opt" in
		a)
			all=1 ;;
		*)
			echo 'Usage: ./rmimgs [-a]' >&2
			exit 1 ;;
	esac
done

if [ $(docker ps -a | wc -l) -gt 1 ]; then
	echo 'Removing all docker containers...'
	[ $(docker ps -a | grep Up | wc -l) -gt 0 ] && docker kill $(docker ps -a | grep Up | awk -F ' ' '{print $1}')
	docker rm $(docker ps -a | tail -n+2 | awk -F ' ' '{print $1}')
fi

if [ $all -eq 1 ]; then
	if [ $(docker images | wc -l) -gt 1 ]; then
		echo 'Removing all docker images...'
		docker rmi -f $(docker images | tail -n+2 | awk -F ' ' '{print $3}')
	fi
else
	if [ $(docker images | grep '<none>' | wc -l) -gt 0 ]; then
		echo 'Removing untagged docker images...'
		docker rmi -f $(docker images | grep '<none>' | awk -F ' ' '{print $3}')
	fi
fi

echo 'Done'
