#!/bin/bash

set -e


[ $UID -ne 0 ] && {
	echo 'This script must be executed with root privilege.'
	exit 1
}

hash pacstrap &>/dev/null || {
	echo "Could not find pacstrap. Run pacman -S arch-install-scripts"
	exit 1
}

cd "$(dirname "$0")"
DATE=$(date +'%Y.%m.%d')
ROOTFS=$(mktemp -d ${TMPDIR:-/var/tmp}/rootfs-archlinux-XXXXXXXXXX)
chmod 755 "$ROOTFS"
PKGIGNORE=(
	cryptsetup
	device-mapper
	dhcpcd
	iproute2
	jfsutils
	linux
	linux-firmware
	lvm2
	man-db
	man-pages
	mdadm
	nano
	netctl
	openresolv
	pciutils
	pcmciautils
	reiserfsprogs
	s-nail
	systemd-sysvcompat
	usbutils
	vi
	xfsprogs
)
IFS=' '
PKGIGNORE="${PKGIGNORE[*]}"
unset IFS
PACMAN_EXTRA_PKGS=''
export LANG='en_US.UTF-8'

pacstrap -C ./pacman.conf -cdG "$ROOTFS" base haveged $PACMAN_EXTRA_PKGS
pacman --root "$ROOTFS" --noconfirm -Rcn $PKGIGNORE

arch-chroot "$ROOTFS" /bin/sh -c "haveged -w 1024; pacman-key --init; pkill haveged; pacman -Rsn --noconfirm haveged; pacman-key --populate archlinux; pkill gpg-agent"
arch-chroot "$ROOTFS" /bin/sh -c "ln -sf /usr/share/zoneinfo/UTC /etc/localtime"
echo 'en_US.UTF-8 UTF-8' > "$ROOTFS/etc/locale.gen"
arch-chroot "$ROOTFS" locale-gen
cp -f mirrorlist "$ROOTFS/etc/pacman.d/mirrorlist"
arch-chroot "$ROOTFS" /bin/sh -c 'rm -rf /usr/share/man/* /var/cache/pacman/pkg/* /var/lib/pacman/sync/*'

# udev doesn't work in containers, rebuild /dev
DEV="$ROOTFS/dev"
rm -rf "$DEV"
mkdir -p "$DEV"
mknod -m 666  "$DEV/null"    c 1 3
mknod -m 666  "$DEV/zero"    c 1 5
mknod -m 666  "$DEV/random"  c 1 8
mknod -m 666  "$DEV/urandom" c 1 9
mkdir -m 755  "$DEV/pts"
mkdir -m 1777 "$DEV/shm"
mknod -m 666  "$DEV/tty"     c 5 0
mknod -m 600  "$DEV/console" c 5 1
mknod -m 666  "$DEV/tty0"    c 4 0
mknod -m 666  "$DEV/full"    c 1 7
mknod -m 600  "$DEV/initctl" p
mknod -m 666  "$DEV/ptmx"    c 5 2
ln -sf /proc/self/fd "$DEV/fd"

tar --numeric-owner --xattrs --acls -f - -C "$ROOTFS" -c . | docker import - kyechou/archlinux
rm -rf "$ROOTFS"
docker run --rm -it kyechou/archlinux echo Success.
